id: opecha:P000571
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG04059
  title: རི་བོ་དགེ་ལྡན་པའི་ཆོས་སྤྱོད་ཁག་གཅིག་གི་འགྲེལ་བ།
  volume:
    d8c2a9c31a8e414485af971f762a5bc4:
      image_group_id: I00KG04075
      title: Volume 1 of ri bo dge ldan pa'i chos spyod khag gcig gi 'grel ba
      volume_number: 1
      total_pages: 202
  author: ''
ebook_metadata:
  title: རི་བོ་དགེ་ལྡན་པའི་ཆོས་སྤྱོད་ཁག་གཅིག་གི་འགྲེལ་བ།
  author: ''
  sku: P000571
  cover: cover.jpg
  layers:
  - pagination
