id: P000571
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG04059
  title: རི་བོ་དགེ་ལྡན་པའི་ཆོས་སྤྱོད་ཁག་གཅིག་གི་འགྲེལ་བ།
  author: ''
  volumes:
    d8c2a9c31a8e414485af971f762a5bc4:
      image_group_id: I00KG04075
      title: Volume 1 of ri bo dge ldan pa'i chos spyod khag gcig gi 'grel ba
      volume_number: 1
      total_pages: 202
      base_file: v001.txt
